ClassList: 
Brigid Camargo
Milissa Plaster
Lessie Binns
Jenae Knisely
Kirk Yang
Marcelino Montiel
Dick Minick
Debbra Lindeman
Gregorio Mcculley
Pamella Pepper
Ronda Birden
Alysia Stiefel
Elayne Krajewski
Alfonzo Kohr
Vanesa Frary
Reatha Netherland
Mabelle Lefever
Audra Benbow
Glendora Mcclaren
Daisy Bear
Azzie Snowden
Candance Yamashita
Wilma Rozek
Barabara Figgs
Vincenzo Santini
Nida Merriam
Regina Feeley
Cathie Reichling
Dorris Perrone
Desirae Burleson
